export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_IMAGES = "GET_IMAGES";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE";
